# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d815af435ac67f62203b4af8b1a482c99d6ff1f9a0176ce106b9cd74fa5f455c04688c95a8c25a22c6936f6668ebcf43519e724db395fe4025e92c6f1228902c

test:
  secret_key_base: 41a17f239122794eefa21314542d7eadd818f1d0be9642d66664cf3186033be7217ea6df4da06a199b834057cee0618c14ef5e408c87517960b24d22309678b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
